//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagerApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProjectManagerAppEntities1 : DbContext
    {
        public ProjectManagerAppEntities1()
            : base("name=ProjectManagerAppEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
    
        public virtual ObjectResult<Logs_ResultSheet_Result> Logs_ResultSheet(Nullable<int> developerId)
        {
            var developerIdParameter = developerId.HasValue ?
                new ObjectParameter("DeveloperId", developerId) :
                new ObjectParameter("DeveloperId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Logs_ResultSheet_Result>("Logs_ResultSheet", developerIdParameter);
        }
    
        public virtual ObjectResult<Project_ResultSheet_Result> Project_ResultSheet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Project_ResultSheet_Result>("Project_ResultSheet");
        }
    
        public virtual int ReportSave_Complete(string logXML)
        {
            var logXMLParameter = logXML != null ?
                new ObjectParameter("LogXML", logXML) :
                new ObjectParameter("LogXML", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ReportSave_Complete", logXMLParameter);
        }
    }
}
