//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagerApp.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectsDeveloper
    {
        public int Id { get; set; }
        public int DeveloperId { get; set; }
        public int ProjectsId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Project Project { get; set; }
    }
}
